#Роль
- type: job
  id: Blueshield
  name: Офицер Синий Щит
  description: Защищайте командный состав и ВИП персон Центрального Командования
  playTimeTracker: JobBlueshield
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000 # 5 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 # 2 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400 # 4 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 7200 # 2 hours
    - !type:AgeRequirement
      requiredAge: 21 # Adventure
# Adventure-edit-start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Synth
      - Zerah
      - PigMan
      - Vox
# Adventure-edit-end
  startingGear: BlueshieldGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial

- type: playTimeTracker
  id: JobBlueshield

#Гир
- type: startingGear
  id: BlueshieldGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: BlueshieldPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash

#Карта
- type: entity
  parent: IDCardStandard
  id: BlueshieldIDCard
  name: ID карта офицера синий щит
  components:
  - type: Sprite
    sprite: _GS/Roles/blueshield/PDA/ID.rsi
    layers:
    - state: silver
    - state: idblueshield
  - type: Item
    heldPrefix: silver
  - type: PresetIdCard
    job: Blueshield

- type: entity
  name: кпк офицера синий щит
  parent: BasePDA
  id: BlueshieldPDA
  description: Пахнет безопасностью.
  components:
  - type: Pda
    id: BlueshieldIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-blueshield
  - type: PdaBorderColor
    borderColor: "#3c485a"
    accentVColor: "#3c485a"
  - type: Icon
    state: pda-blueshield

#Спавнер
- type: entity
  id: SpawnPointBlueshield
  parent: SpawnPointJobBase
  name: Офицер Синий Щит
  suffix: AdvRoles, AdvMapping
  components:
  - type: SpawnPoint
    job_id: Blueshield
  - type: Sprite
    sprite: _GS/Roles/blueshield/SpawnPoint.rsi
    layers:
      - state: green
      - state: Blueshield

#Иконка
- type: jobIcon
  parent: JobIcon
  id: JobIconBlueshield
  icon:
    sprite: /Textures/_GS/Roles/blueshield/PDA/JobIcons.rsi
    state: BlueShieldOfficer
  jobName: синий щит

#Шкаф
- type: entity
  id: LockerBlueshield
  parent: LockerBase
  name: шкаф офицера синий щит
  components:
  - type: Appearance
  - type: EntityStorageVisuals
    stateBaseClosed: Blueshield
    stateDoorOpen: blueshield_open
    stateDoorClosed: Blueshield_door
  - type: AccessReader
    access: [ [ "Command" ] ]

- type: entity
  id: LockerBlueshieldFilledHardsuit
  suffix: Заполненный, Скафандр, AdvRoles, AdvMapping
  parent: LockerBlueshield
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHatBlueshieldBeret
      - id: HandheldGPSBasic
      - id: MedkitCombatFilled
      - id: MedkitFilled
      - id: HandheldCrewMonitor
      - id: ClothingOuterHardsuitBlueshield
      - id: TrackingImplanter
      - id: TrackingImplanter
      - id: TrackingImplanter
      - id: TrackingImplanter
      - id: RubberStampblueshield
      - id: WeaponX2DualphaseEnergyLaserGun
      - id: ClothingBeltSheathBS
#      - id: BSuplink Устарел и заменён на торгомат

#Печать ОСЩ by raidgo
# окак, будем знать --гусь
- type: entity
  name: печать офицера синий щит
  description: Печать из резины, для проставления печатей на важных документах.
  parent: RubberStampBase
  id: RubberStampblueshield
  suffix: Genesis
  components:
  - type: Stamp
    stampedName: Синий Щит
    stampedColor: "#233D57"
    stampState: "paper_stamp-lawyer"
  - type: Sprite
    state: stamp-lawyer
