#Рюкзак
- type: entity
  parent: ClothingBackpack
  id: ClothingBackpackBlueshield
  name: рюкзак офицера синего щита
  description: Особенный рюкзак для элитного офицера синий щит! А стоп... он же пассажирский.. или нет?
  components:
  - type: Sprite
    sprite: _GS/Roles/blueshield/Clothing/Backpacks/blueshield.rsi

#Вещмешок
- type: entity
  parent: ClothingBackpackDuffel
  id: ClothingBackpackDuffelBlueshield
  name: вещмешок офицера синий щит.
  description: Большая сумка для хранения ору.. то есть защиты капитана.
  components:
  - type: Sprite
    sprite: _GS/Roles/blueshield/Clothing/Backpacks/BSbag.rsi

#Сумка
- type: entity
  parent: ClothingBackpackSatchel
  id: ClothingBackpackSatchelBlueshield
  name: сумка офицера синий щит
  description: Маленькая и удобная, а главное модная.
  components:
  - type: Sprite
    sprite: _GS/Roles/blueshield/Clothing/Backpacks/BSsatchel.rsi
