- type: entity
  parent: VendingMachine
  id: VendingMachineBSrobe
  name: СинеШкаф
  suffix: AdvMapping
  description: Торговый автомат для одежды, связанной с охраной и безопасностью глав станции!
  components:
  - type: VendingMachine
    pack: BSrobeInventory
    offState: off
    brokenState: broken
    normalState: normal-unshaded
  - type: SpeakOnUIClosed
    pack: GenericVendGoodbyes
  - type: Sprite
    sprite: _GS/Roles/blueshield/VendingRobe.rsi
    layers:
    - state: "off"
      map: ["enum.VendingMachineVisualLayers.Base"]
    - state: "off"
      map: ["enum.VendingMachineVisualLayers.BaseUnshaded"]
      shader: unshaded
    - state: panel
      map: ["enum.WiresVisualLayers.MaintenancePanel"]
  - type: PointLight
    radius: 1.5
    energy: 1.6
    color: "#1e90ff"
  - type: AccessReader
    access: [["Command"]]
